<?php

namespace AppBundle\Repository;

/**
 * Product_PictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_PictureRepository extends \Doctrine\ORM\EntityRepository
{
}
