<?php

namespace AppBundle\Repository;

/**
 * Product_CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_CommentRepository extends \Doctrine\ORM\EntityRepository
{
}
